import assert from "node:assert/strict";
import { pathToFileURL } from "node:url";
import { join } from "node:path";

const playwrightRoot = process.env.PLAYWRIGHT_MODULE;
if (!playwrightRoot) throw new Error("Set PLAYWRIGHT_MODULE to a local Playwright package directory.");
const playwright = await import(pathToFileURL(join(playwrightRoot, "index.js")).href);
const { chromium } = playwright.default || playwright;
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.setDefaultTimeout(8000);
await page.goto(process.env.CASEFILE_HARNESS || "http://localhost:5187/", { waitUntil: "networkidle" });
const frame = page.frameLocator("#app");
await frame.locator("#workspace").waitFor();
await page.waitForTimeout(1500);
const initial = await frame.locator("body").innerText();
assert.match(initial, /Every room|Casefile/);
assert.match(initial, /Anna synced|Device save/);
await frame.getByRole("link", { name: "Open first dossier" }).click();
await frame.locator('[data-action="start-case"]').click();
await page.waitForTimeout(500);
await frame.locator('[data-action="inspect-clue"]').first().click();
await frame.locator('[data-action="close-dialog"]').last().click();
await frame.locator('a[href="#/board"]').click();
assert.match(await frame.locator("body").innerText(), /Evidence board|1\/6 catalogued/);
await page.reload({ waitUntil: "networkidle" });
await frame.locator("#workspace").waitFor();
assert.match(await frame.locator("body").innerText(), /Resume investigation|The Last Departure/);
await browser.close();
console.log("Anna dev harness smoke passed: runtime connection, hosted UI, clue interaction, and active-game recovery.");
